FROM ubuntu
RUN apt-get update --fix-missing
RUN apt-get -y install tzdata
RUN apt-get -y install apache2
RUN apt-get -y install php7.4
RUN apt-get -y install git
RUN apt-get -y install make
RUN apt-get -y install libhtml-parser-perl
RUN apt-get -y install postgresql-client
RUN apt-get -y install php-pgsql

